# Generated by Django 3.1.2 on 2020-10-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='code_type',
        ),
        migrations.AlterField(
            model_name='registration',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
