# Generated by Django 3.1.2 on 2020-10-28 16:46

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='BD', max_length=2)),
                ('category', models.CharField(blank=True, choices=[('1', 'Not specified'), ('2', 'Asian'), ('3', 'Indian'), ('4', 'Mexican'), ('5', 'Swiss'), ('6', 'Comfort Food'), ('7', 'Italian'), ('8', 'American')], default='1', max_length=20)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('website', models.URLField(blank=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('pricelevel', models.CharField(blank=True, choices=[('1', 'Cheap'), ('2', 'Intermediate'), ('3', 'Expensive'), ('4', 'Godly Expensive')], default='2', max_length=4)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('openhours', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
