# Generated by Django 3.1.2 on 2020-10-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('pricelevel', models.CharField(blank=True, choices=[('1', 'Cheap'), ('2', 'Intermediate'), ('3', 'Expensive'), ('4', 'Godly Expensive')], default='2', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
