# Generated by Django 3.1.2 on 2020-10-27 14:27

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Not specified'), ('2', 'Asian'), ('3', 'Indian'), ('4', 'Mexican'), ('5', 'Swiss'), ('6', 'Comfort Food'), ('7', 'Italian'), ('8', 'American')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
