# Generated by Django 3.1.2 on 2020-10-27 17:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20201027_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='openhours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='BD', max_length=2),
        ),
    ]
